const PORT = process.env.PORT;
const MONGO_URI = process.env.MONGO_URI;
const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID;
const MSG91_AUTH_KEY = process.env.MSG91_AUTH_KEY;
const MSG91_TEMPLATE_ID = process.env.MSG91_TEMPLATE_ID;
const MSG91_SENDER_ID = process.env.MSG91_SENDER_ID;
const JWT_SECRET = process.env.JWT_SECRET;
const JWT_EXPIRES_IN = process.env.JWT_EXPIRES_IN;
const CLOUDINARY_NAME = process.env.CLOUDINARY_NAME;
const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY;
const CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET;

const OTP_API_KEY = process.env.OTP_API_KEY;
const OTP_CAMPAIGN = process.env.OTP_CAMPAIGN;
const OTP_ROUTE = process.env.OTP_ROUTE;
const OTP_SENDER = process.env.OTP_SENDER;
const OTP_TEMPLATE = process.env.OTP_TEMPLATE;
const OTP_PE_ID = process.env.OTP_PE_ID;
const APP_BASE_URL = process.env.APP_BASE_URL;

const SUPER_ADMIN_PASSWORD = process.env.SUPER_ADMIN_PASSWORD;
const ANDROID_APP_SIGNATURE = process.env.ANDROID_APP_SIGNATURE;

module.exports = {
  PORT,
  MONGO_URI,
  GOOGLE_CLIENT_ID,
  MSG91_AUTH_KEY,
  MSG91_TEMPLATE_ID,
  MSG91_SENDER_ID,
  JWT_SECRET,
  JWT_EXPIRES_IN,
  CLOUDINARY_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  OTP_API_KEY,
  OTP_CAMPAIGN,
  OTP_ROUTE,
  OTP_SENDER,
  OTP_TEMPLATE,
  OTP_PE_ID,
  APP_BASE_URL,
  SUPER_ADMIN_PASSWORD,
  ANDROID_APP_SIGNATURE,
};
